name: "throttle"
version: "0.1.0"
usage: "Proxy app for containers"
description: "Avoid containers overwhelming by throttle proxy. "
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/helm-throttle.sh"
hooks:
  install: "python3 -m venv $HELM_PLUGIN_DIR/venv; source $HELM_PLUGIN_DIR/venv/bin/activate; pip install -r $HELM_PLUGIN_DIR/requirements.txt;"
  update: "python3 -m venv $HELM_PLUGIN_DIR/venv; source $HELM_PLUGIN_DIR/venv/bin/activate; pip install -r $HELM_PLUGIN_DIR/requirements.txt;"
