name: "throttle"
version: "1.0.0"
usage: "throttle your deployments"
description: "A Helm plugin to throttle controllers during upgrades."
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/helm-throttle.sh"
hooks:
  install: "python3 -m venv $HELM_PLUGIN_DIR/venv; source $HELM_PLUGIN_DIR/venv/bin/activate; pip install -r $HELM_PLUGIN_DIR/requirements.txt;"
  update: "python3 -m venv $HELM_PLUGIN_DIR/venv; source $HELM_PLUGIN_DIR/venv/bin/activate; pip install -r $HELM_PLUGIN_DIR/requirements.txt;"
